from urllib.request import urlopen
from bs4 import BeautifulSoup
q16=[['2','general','dilute','spill','figure','usual','dim','routine','warehouse','eliminate','crew','deny','barrier','scream','tradition','sensitive','pedestrian','swallow','glance','glare','irritate','tragic','cruel','deprive','fold','conscious','trial','interfere','tribe','temporary','profound','council','distinguish','adolescent','errand','associate','welfare','arctic','statement','capture','prevail'],
['2','widespread','noble','result','repair','fade','candidate','progress','ideal','weapon','crop','drastic','ethnic','reinforcement','foretell','wonder','wholesale','pile','debt','protect','representative','infection','shift','stiffen','excess','endanger','strict','adjust','appliance','peer','furthermore','renew','command','germ','ecosystem','atom','fame','realize','oral','enrich','drift'],
['2','avoid','thread','outstanding','dynasty','mislead','scatter','dedicate','gamble','initial','temper','sink','undoubtedly','entire','raft','confront','minimal','beard','soak','haste','craft','crush','cease','destiny','review','hardship','ceiling','escape','unify','valid','combat','dispose','bump','exist','primary','optimal','genre','hydrogen','erase','perspective','doom'],
['2','vital','sphere','incident','inherit','session','disgrace','obvious','crawl','moderate','scratch','budget','diabetes','graze','congestion','fragile','constitute','myth','flow','fur','investigate','indifferent','barter','strain','circular','ingredient','chilly','dismiss','ancestor','geometry','fierce','glacier','vague','urge','rough','celebrity','content','antique','obstacle','profit','editorial'],
['2','abolish','tissue','assure','lord','form','substitute','gender','scan','innovation','pottery','opponent','layer','present','property','fertile','justify','emperor','polish','dwell','flavor','chore','imprint','rehearsal','heritage','fossil','strive','glitter','radiant','carve','exclaim','decay','asset','protein','portray','backward','administer','translate','wage','refresh','subscribe'],
['2','merit','famine','launch','pill','conference','immune','accuse','raw','enhance','superior','intimate','string','reception','cope','overwhelm','loan','apply','obedient','majesty','procedure','shrug','bond','vicious','angle','cherish','subtle','eternal','depict','shrink','radical','colleague','caution','transmit','persist','discard','reverse','copper','cattle','orbit','therapy'],
['2','experience','panic','strategy','optimistic','attract','murder','hence','fundamental','architecture','loyal','territory','humid','wilderness','pretend','category','graduate','funeral','delicate','prefer','inflate','outcome','adequate','humiliation','physician','ban','joint','flush','via','omit','passage','despair','vessel','alert','restore','compact','passive','likewise','marble','astonish','classify'],
['2','prepare','infinite','transaction','roam','sufficient','decent','stable','behalf','concern','distortion','sympathy','bud','principal','symbolic','by-product','municipal','anxiety','phenomenon','edible','devote','federal','peasant','suffer','diminish','trivial','jealous','tablet','exclude','trade','flexible','liquid','tenant','contend','worthwhile','anticipate','pavement','outlook','nominate','desert','sacred'],
['2','support','collapse','revise','trigger','suggest','martial','control','monologue','mammal','deliberate','internal','plot','resent','rod','abrupt','partial','diverse','mutual','refine','priceless','dynamic','fate','nerve','pursue','prompt','Atlantic','suspend','weird','industry','booth','iceberg','prescribe','monetary','erupt','superb','insult','gloom','gaze','distraction','supreme'],
['2','context','cheer','complete','miserable','race','tease','dominate','aggressive','vehicle','cure','complain','attribute','brochure','foster','force','psychologist','nest','postpone','gain','rob','curriculum','abuse','sew','unemployed','masculine','breakdown','frown','disguise','astound','blueprint','dictator','rear','assessment','output','crucial','sermon','paralysis','sprout','deck','tin'],
['2','reform','hostile','deal','characteristic','recruit','respect','maintain','await','workshop','concrete','patient','lease','convention','racial','devastate','variable','reap','satisfy','overlook','rule','deliver','perseverance','reject','fatal','nourish','remove','bay','invert','stun','tension','particular','reign','bulletin','crack','fluid','startle','affair','discourage','dawn','compensate'],
['2','convert','peculiar','strike','sake','suppress','choke','core','folktale','contribute','simultaneously','spear','range','renowned','groom','era','supernatural','withdraw','tender','immigrate','instinct','dignity','gigantic','notify','meditate','animate','mow','prevent','evolve','bilingual','chase','mischief','afflict','discriminate','literate','exemplify','coherent','adhere','intolerable','judge','fountain'],
['2','bold','conceal','compliment','retreat','summit','compulsive','troop','clinic','alter','banner','conceive','formulate','durability','vow','destroy','malnutrition','shallow','relate','face','undergo','promote','boast','weep','neutral','grasp','stain','overall','incentive','superstition','float','colony','tendency','absurd','applause','dormitory','wrestle','conduct','sensation','prone','Confucian'],
['2','draft','subtract','crude','impulse','supplement','utmost','velocity','proficient','tame','accumulate','molecule','embody','manage','equity','dismay','violate','diagnose','ambitious','adapt','borrow','reservoir','attend','conform','trim','spacious','navigate','weave','tray','boundary','consist','motive','ceremony','prominent','attack','inferior','confine','rigid','dispatch','archeology','diameter'],
['2','anecdote','damp','propriety','script','blame','possibility','earn','discuss','pledge','sibling','cost','lay','geology','flourish','detect','discharge','temperate','thorough','soar','undertake','mock','panel','disclose','linguistic','exhibit','remedy','symptom','feed','intact','sophomore','invent','remind','awkward','sole','grind','pillar','expose','explode','closet','illusion']]

for a in range(15):
    for i in range(len(q16[0])):
        if i==0:
            print(a+16,"과")
        elif a==8 and i==26:
            print('Atlantic','\n','the Atlantic short for Atlantic Ocean','\n')
        elif a==11 and i==8:
            print('folktale','\n',' A tale or story that is part of the oral tradition of a people or a place.','\n')
        elif a==12 and i==40:
            print('Confucian','\n','of or relating to the doctrines of Confucius','\n')
        else:
            html = urlopen("https://endic.naver.com/search.nhn?sLn=kr&isOnlyViewEE=Y&query="+q16[a][i])
            soup = BeautifulSoup(html, "html.parser")
            title_data = soup.find('m')
            print(q16[a][i],'\n',title_data.text,'\n')